### PR TITLE
Update Image Upload Guide

### PR DESCRIPTION
**Pull request by jelaniwoods**
I thought this guide could use some updates to be more consistent and clear by using the syntax and methods we use in the course. 
This branch makes the following changes:
- Update `rake db:migrate` to `rails db:migrate`
- Use `.fetch` instead of brackets
- Be more specific about the switch from local storage to Cloudinary. [This issue](https://piazza.com/class/jqo9y46rrme514?cid=371).
- Change the link to devise from a Gist to a markdown file

### CODE REVIEW

**Comment by raghubetina** [comment]
@jelaniwoods Love this, thank you. Perhaps link to the guide on storing credentials securely for that bit:

https://guides.firstdraft.com/storing-credentials-securely

**Comment by jelaniwoods** [comment]
@raghubetina that's a good idea. I'll add that.

**Comment by LoganDSPrice** [comment]
👍 :shipit:

**Comment by LoganDSPrice** [comment]
Nice changes since I looked last. LGTM

**Comment by raghubetina** [comment]
LGTM :ship:

**Pull request merged**
